version: "3.8"

services:
  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credentials
    ports:
      - 5432:5432
    volumes:
      - credential-db-vol:/var/lib/postgresql/data

volumes:
  credential-db-vol:

networks:
  polypass-network:
    driver: bridge
