package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"fmt"

	model1 "github.com/DO-2K23-26/polypass-microservices/gateway/graph/model"
	"github.com/DO-2K23-26/polypass-microservices/gateway/infrastructure/organizations"
	"github.com/optique-dev/optique"
)

// Parent is the resolver for the parent field.
func (r *folderResolver) Parent(ctx context.Context, obj *model1.Folder) (*model1.Folder, error) {
	folder, err := r.OrganizationsService.GetFolder(obj.ID)
	if err != nil {
		return nil, err
	}
	return FolderToModel(&folder), nil
}

// CreatedBy is the resolver for the createdBy field.
func (r *folderResolver) CreatedBy(ctx context.Context, obj *model1.Folder) (*model1.User, error) {
	folder, err := r.OrganizationsService.GetFolder(obj.ID)
	if err != nil {
		return nil, err
	}
	return &model1.User{
		ID:       folder.CreatedBy,
		Username: "jul",
		Email:    "jul@gmail.com",
	}, nil
}

// Members is the resolver for the members field.
func (r *folderResolver) Members(ctx context.Context, obj *model1.Folder) ([]*model1.User, error) {
	folder, err := r.OrganizationsService.GetFolder(obj.ID)

	if err != nil {
		return nil, err
	}
	members := make([]*model1.User, len(folder.Members))
	for i, member := range folder.Members {
		members[i] = &model1.User{
			ID:       member,
			Username: "jul",
			Email:    "jul@gmail.com",
		}
	}
	return members, nil
}

// Tags is the resolver for the tags field.
func (r *folderResolver) Tags(ctx context.Context, obj *model1.Folder) ([]*model1.Tag, error) {
	panic(fmt.Errorf("not implemented: Tags - tags"))
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, newFolder model1.NewFolder) (*model1.Folder, error) {
	folder, err := r.OrganizationsService.CreateFolder(organizations.CreateFolderRequest{
		Name:        newFolder.Name,
		ParentID:    newFolder.Parent,
		Description: newFolder.Description,
		Icon:        newFolder.Icon,
		CreatedBy:   newFolder.CreatedBy,
	})
	if err != nil {
		return nil, err
	}
	return FolderToModel(&folder), nil
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteFolder - deleteFolder"))
}

// Credentials is the resolver for the credentials field.
func (r *queryResolver) Credentials(ctx context.Context) ([]model1.Credential, error) {
	panic(fmt.Errorf("not implemented: Credentials - credentials"))
}

// Folders is the resolver for the folders field.
func (r *queryResolver) Folders(ctx context.Context) ([]*model1.Folder, error) {
	folders, err := r.OrganizationsService.GetFolders()
	optique.Info(fmt.Sprintf("GetFolders: %v", folders))
	graphql_folders := make([]*model1.Folder, 0)
	if err != nil {
		optique.Error(err.Error())
		return nil, err
	}
	for _, folder := range folders {
		graphql_folders = append(graphql_folders, FolderToModel(&folder))
	}
	optique.Info(fmt.Sprintf("graphql_folders: %v", graphql_folders))
	return graphql_folders, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) ([]*model1.Tag, error) {
	panic(fmt.Errorf("not implemented: Tags - tags"))
}

// SearchFolders is the resolver for the searchFolders field.
func (r *queryResolver) SearchFolders(ctx context.Context, searchQuery string, limit int32, page int32, userID string) (*model1.SearchFoldersResponse, error) {
	panic(fmt.Errorf("not implemented: SearchFolders - searchFolders"))
}

// SearchTags is the resolver for the searchTags field.
func (r *queryResolver) SearchTags(ctx context.Context, searchQuery string, folderID string, limit int32, page int32, userID string) (*model1.SearchTagsResponse, error) {
	panic(fmt.Errorf("not implemented: SearchTags - searchTags"))
}

// SearchCredentials is the resolver for the searchCredentials field.
func (r *queryResolver) SearchCredentials(ctx context.Context, searchQuery string, folderID *string, tagIds []string, limit int32, page int32, userID string) (*model1.SearchCredentialsResponse, error) {
	panic(fmt.Errorf("not implemented: SearchCredentials - searchCredentials"))
}

// Folder is the resolver for the folder field.
func (r *tagResolver) Folder(ctx context.Context, obj *model1.Tag) (*model1.Folder, error) {
	panic(fmt.Errorf("not implemented: Folder - folder"))
}

// CreatedBy is the resolver for the createdBy field.
func (r *tagResolver) CreatedBy(ctx context.Context, obj *model1.Tag) (*model1.User, error) {
	panic(fmt.Errorf("not implemented: CreatedBy - createdBy"))
}

// Folder returns FolderResolver implementation.
func (r *Resolver) Folder() FolderResolver { return &folderResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Tag returns TagResolver implementation.
func (r *Resolver) Tag() TagResolver { return &tagResolver{r} }

type folderResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type tagResolver struct{ *Resolver }
