// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Credential interface {
	IsCredential()
}

type CardCredential struct {
	CardNumber     string  `json:"cardNumber"`
	CreatedAt      string  `json:"createdAt"`
	CustomFields   *string `json:"customFields,omitempty"`
	Cvc            string  `json:"CVC"`
	ExpirationDate string  `json:"expirationDate"`
	ExpiresAt      string  `json:"expiresAt"`
	ID             string  `json:"id"`
	LastReadAt     *string `json:"lastReadAt,omitempty"`
	Note           *string `json:"note,omitempty"`
	OwnerName      string  `json:"ownerName"`
	Title          *string `json:"title,omitempty"`
	UpdatedAt      *string `json:"updatedAt,omitempty"`
	UserIdentifier string  `json:"userIdentifier"`
}

func (CardCredential) IsCredential() {}

type Folder struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Icon        string  `json:"icon"`
	Parent      *Folder `json:"parent,omitempty"`
	CreatedBy   *User   `json:"createdBy"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
	Members     []*User `json:"members"`
	Tags        []*Tag  `json:"tags,omitempty"`
}

type Mutation struct {
}

type NewFolder struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Icon        string  `json:"icon"`
	Parent      *string `json:"parent,omitempty"`
	CreatedBy   string  `json:"createdBy"`
}

type PasswordCredential struct {
	CreatedAt      string  `json:"createdAt"`
	ExpiresAt      string  `json:"expiresAt"`
	UpdatedAt      *string `json:"updatedAt,omitempty"`
	LastReadAt     *string `json:"lastReadAt,omitempty"`
	Note           *string `json:"note,omitempty"`
	Password       string  `json:"password"`
	Title          *string `json:"title,omitempty"`
	UserIdentifier string  `json:"userIdentifier"`
	ID             string  `json:"id"`
	DomainName     string  `json:"domainName"`
	CustomFields   *string `json:"customFields,omitempty"`
}

func (PasswordCredential) IsCredential() {}

type Query struct {
}

type SSHCredential struct {
	CreatedAt      string  `json:"createdAt"`
	ExpiresAt      string  `json:"expiresAt"`
	UpdatedAt      *string `json:"updatedAt,omitempty"`
	LastReadAt     *string `json:"lastReadAt,omitempty"`
	Note           *string `json:"note,omitempty"`
	PublicKey      string  `json:"publicKey"`
	PrivateKey     string  `json:"privateKey"`
	Title          *string `json:"title,omitempty"`
	UserIdentifier string  `json:"userIdentifier"`
	ID             string  `json:"id"`
	Hostname       string  `json:"hostname"`
	CustomFields   *string `json:"customFields,omitempty"`
}

func (SSHCredential) IsCredential() {}

type Tag struct {
	Name      string  `json:"name"`
	Color     string  `json:"color"`
	Folder    *Folder `json:"folder"`
	CreatedBy *User   `json:"createdBy"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
