definitions:
  fiber.Map:
    additionalProperties: true
    type: object
  http.CreateCardCredentialOpts:
    properties:
      card_number:
        type: integer
      custom_fields:
        additionalProperties: {}
        type: object
      cvc:
        type: integer
      expiration_date:
        type: string
      note:
        type: string
      owner_name:
        type: string
      title:
        type: string
    type: object
  http.CreatePasswordCredentialOpts:
    properties:
      custom_fields:
        additionalProperties: {}
        type: object
      domain_name:
        type: string
      note:
        type: string
      password:
        type: string
      title:
        type: string
    type: object
  http.CreateSSHCredentialOpts:
    properties:
      custom_fields:
        additionalProperties: {}
        type: object
      hostname:
        type: string
      note:
        type: string
      private_key:
        type: string
      public_key:
        type: string
      title:
        type: string
    type: object
  types.CardCredential:
    properties:
      card_number:
        type: integer
      created_at:
        type: string
      custom_fields:
        additionalProperties: {}
        type: object
      cvc:
        type: integer
      expiration_date:
        type: string
      expires_at:
        type: string
      id:
        type: string
      last_read_at:
        type: string
      note:
        type: string
      owner_name:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user_identifier:
        type: string
    type: object
  types.PasswordCredential:
    properties:
      created_at:
        type: string
      custom_fields:
        additionalProperties: {}
        type: object
      domain_name:
        type: string
      expires_at:
        type: string
      id:
        type: string
      last_read_at:
        type: string
      note:
        type: string
      password:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user_identifier:
        type: string
    type: object
  types.SSHKeyCredential:
    properties:
      created_at:
        type: string
      custom_fields:
        additionalProperties: {}
        type: object
      expires_at:
        type: string
      hostname:
        type: string
      id:
        type: string
      last_read_at:
        type: string
      note:
        type: string
      private_key:
        type: string
      public_key:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user_identifier:
        type: string
    type: object
info:
  contact:
    email: tristan-mihai.radulescu@etu.umontpellier.fr
    name: Tristan-Mihai Radulescu
    url: https://github.com/DO-2K23-26
  description: Polypass Credentials Microservice
  title: Polypass Credentials Microservice
  version: 0.1.0
paths:
  /credentials/card:
    delete:
      consumes:
      - application/json
      description: Delete a list of Card credentials
      parameters:
      - description: Comma-separated list of credential IDs
        in: query
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Delete card credentials
      tags:
      - credentials
    get:
      consumes:
      - application/json
      description: Get a list of card credentials
      parameters:
      - description: Comma-separated list of card IDs
        in: query
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.CardCredential'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Get card credentials
      tags:
      - card
    post:
      consumes:
      - application/json
      description: Create a card credential
      parameters:
      - description: Create card credential options
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/http.CreateCardCredentialOpts'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.CardCredential'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Create card credential
      tags:
      - credentials
  /credentials/card/:id:
    put:
      consumes:
      - application/json
      description: Update a card credential
      parameters:
      - description: Update card credential options
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/http.CreateCardCredentialOpts'
      - description: Credential ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.CardCredential'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Update card credential
      tags:
      - credentials
  /credentials/password:
    delete:
      consumes:
      - application/json
      description: Delete a list of password credentials
      parameters:
      - description: Comma-separated list of credential IDs
        in: query
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Delete password credentials
      tags:
      - credentials
    get:
      consumes:
      - application/json
      description: Get a list of password credentials
      parameters:
      - description: Comma-separated list of credential IDs
        in: query
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.PasswordCredential'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Get password credentials
      tags:
      - credentials
    post:
      consumes:
      - application/json
      description: Create a password credential
      parameters:
      - description: Create password credential options
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/http.CreatePasswordCredentialOpts'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.PasswordCredential'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Create password credential
      tags:
      - credentials
  /credentials/password/:id:
    put:
      consumes:
      - application/json
      description: Update a password credential
      parameters:
      - description: Update password credential options
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/http.CreatePasswordCredentialOpts'
      - description: Credential ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.PasswordCredential'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Update password credential
      tags:
      - credentials
  /credentials/sshkey:
    delete:
      consumes:
      - application/json
      description: Delete a list of SSHKey credentials
      parameters:
      - description: Comma-separated list of credential IDs
        in: query
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Delete SSHKey credentials
      tags:
      - credentials
    get:
      consumes:
      - application/json
      description: Get a list of SSHKey credentials
      parameters:
      - description: Comma-separated list of credential IDs
        in: query
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.SSHKeyCredential'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Get SSHKey credentials
      tags:
      - credentials
    post:
      consumes:
      - application/json
      description: Create a SSHKey credential
      parameters:
      - description: Create SSHKey credential options
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/http.CreateSSHCredentialOpts'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.SSHKeyCredential'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Create SSHKey credential
      tags:
      - credentials
  /credentials/sshkey/:id:
    put:
      consumes:
      - application/json
      description: Update a SSHKey credential
      parameters:
      - description: Update SSHKey credential options
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/http.CreateSSHCredentialOpts'
      - description: Credential ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.SSHKeyCredential'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Update SSHKey credential
      tags:
      - credentials
swagger: "2.0"
