definitions:
  fiber.Map:
    additionalProperties: true
    type: object
  http.CreatePasswordCredentialOpts:
    properties:
      custom_fields:
        additionalProperties: {}
        type: object
      domain_name:
        type: string
      note:
        type: string
      password:
        type: string
      title:
        type: string
    type: object
  types.PasswordCredential:
    properties:
      created_at:
        type: integer
      custom_fields:
        additionalProperties: {}
        type: object
      domain_name:
        type: string
      expires_at:
        type: integer
      id:
        type: string
      last_read_at:
        type: integer
      note:
        type: string
      password:
        type: string
      title:
        type: string
      updated_at:
        type: integer
      user_identifier:
        type: string
    type: object
info:
  contact:
    email: tristan-mihai.radulescu@etu.umontpellier.fr
    name: Tristan-Mihai Radulescu
    url: https://github.com/DO-2K23-26
  description: Polypass Credentials Microservice
  title: Polypass Credentials Microservice
  version: 0.1.0
paths:
  /credentials/password:
    delete:
      consumes:
      - application/json
      description: Delete a list of password credentials
      parameters:
      - description: Comma-separated list of credential IDs
        in: query
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Delete password credentials
      tags:
      - credentials
    get:
      consumes:
      - application/json
      description: Get a list of password credentials
      parameters:
      - description: Comma-separated list of credential IDs
        in: query
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.PasswordCredential'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Get password credentials
      tags:
      - credentials
    post:
      consumes:
      - application/json
      description: Create a password credential
      parameters:
      - description: Create password credential options
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/http.CreatePasswordCredentialOpts'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.PasswordCredential'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Create password credential
      tags:
      - credentials
  /credentials/password/:id:
    put:
      consumes:
      - application/json
      description: Update a password credential
      parameters:
      - description: Update password credential options
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/http.CreatePasswordCredentialOpts'
      - description: Credential ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.PasswordCredential'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Update password credential
      tags:
      - credentials
swagger: "2.0"
