version: '3.8'

# This docker-compose file sets up the Polypass microservices infrastructure
# Kafka is configured to use KRaft mode (without Zookeeper)

services:
  # EventStoreDB for storing events and metrics
  eventstoredb:
    image: eventstore/eventstore:latest
    container_name: polypass-eventstoredb
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    volumes:
      - eventstoredb_data:/var/lib/eventstore
    networks:
      - polypass-network

  # Kafka for event streaming with KRaft mode
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: polypass-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      # KRaft mode specific settings
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - polypass-network

  # Statistics service
  statistics-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: polypass-statistics-service
    depends_on:
      - eventstoredb
      - kafka
    ports:
      - "8081:8080"
    environment:
      EVENTSTOREDB_CONNECTION_STRING: esdb://eventstoredb:2113?tls=false
      KAFKA_BOOTSTRAP: kafka:29092
      KAFKA_GROUP_ID: statistics-service
      HTTP_LISTEN_ADDRESS: :8080
    networks:
      - polypass-network
    restart: on-failure

networks:
  polypass-network:
    driver: bridge

volumes:
  eventstoredb_data:
  kafka_data:
