# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hugo08/authz-service
  pullPolicy: IfNotPresent
  tag: 0.0.3

authzed:
  host: "dev:50051"
  apiKey: "averysecretpresharedkey"

kafka:
  clientId: "authz-service"
  host: "kafka.confluent.svc.cluster.local:9092"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
