services:
  elasticsearch:
    image: elasticsearch:8.17.4
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=search-password
      - ES_PORT=9200
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      

volumes:
  esdata:
    driver: local
